CUDA_VISIBLE_DEVICES=0,1,2,3 accelerate launch \
    --main_process_port 20331 \
    train_sp.py \
    --base_model_name_or_path /mnt/data/models/deepseek-ai/deepseek-coder-1.3b-instruct \
    --device cuda \
    --mm_projector_type mlp2x_gelu \
    --encoder_hidden_size 384 \
    --decoder_hidden_size 2048 \
    --n_tokens 10 \
    --data_path ./dataset/train_new.json \
    --torch_dtype float32 \
    --output_dir ./checkpoints/new/10token_sp_1e-3_1x16 \
    --num_train_epochs 4 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 24000 \
    --save_total_limit 1 \
    --learning_rate 1e-3 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
